# Funding model platforms. Uncomment and fill in the ones you use.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Cosm1cBug]      # GitHub Sponsors
# ko_fi:        cosm1cbug
# buy_me_a_coffee: cosm1cbug
# patreon:      cosm1cbug
# open_collective: echofox
# custom: ['https://yourdomain/donate']
